# HTTP rules for User

type: google.api.Service
config_version: 3

# Name of the service configuration.
name: android.apigateway.cheers-a275e.cloud.goog

# HTTP rules define translation from HTTP/REST/JSON to gRPC. With these rules
# HTTP/REST/JSON clients will be able to call the User service.
http:
  rules:
    # Party Service
    - selector: cheers.party.v1.PartyService.CreateParty
      post: /v1/parties
    - selector: cheers.party.v1.PartyService.GetParty
      get: /v1/parties
    - selector: cheers.party.v1.PartyService.UpdateParty
      patch: /v1/parties
    - selector: cheers.party.v1.PartyService.DeleteParty
      delete: /v1/parties
    - selector: cheers.party.v1.PartyService.FeedParty
      get: /v1/parties/feed

    # Post Service
    - selector: cheers.post.v1.PostService.CreatePost
      post: /v1/posts
    - selector: cheers.post.v1.PostService.GetPost
      get: /v1/posts
    - selector: cheers.post.v1.PostService.UpdatePost
      patch: /v1/posts
    - selector: cheers.post.v1.PostService.DeletePost
      delete: /v1/posts
    - selector: cheers.post.v1.PostService.FeedParty
      get: /v1/posts/feed