type: google.api.Service
config_version: 3
name: android-2c1jeuamu4xtp.apigateway.cheers-a275e.cloud.goog
title: Cheers API
endpoints:
  - name: android-2c1jeuamu4xtp.apigateway.cheers-a275e.cloud.goog
    allow_cors: true
apis:
  - name: cheers.user.v1.UserService
  - name: cheers.post.v1.PostService
  - name: cheers.party.v1.PartyService
  - name: cheers.chat.v1.ChatService
  - name: cheers.story.v1.StoryService
  - name: cheers.activity.v1.ActivityService
  - name: cheers.notification.v1.NotificationService
  - name: cheers.ticket.v1.TicketService
  - name: cheers.comment.v1.CommentService
  - name: cheers.friendship.v1.FriendshipService
usage:
  rules:
    # All methods can be called without an API Key.
    - selector: "*"
      allow_unregistered_calls: true
authentication:
  providers:
    - id: firebase
      jwks_uri: https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com
      issuer: https://securetoken.google.com/cheers-a275e
      audiences: "cheers-a275e"
  rules:
    - selector: "*"
      requirements:
        - provider_id: firebase
backend:
  rules:
    # User Service methods
    - selector: cheers.user.v1.*
      address: grpcs://user-service-r3a2dr4u4a-nw.a.run.app

    # Party Service methods
    - selector: cheers.party.v1.*
      address: grpcs://party-service-r3a2dr4u4a-nw.a.run.app

    # Post Service methods
    - selector: cheers.post.v1.*
      address: grpcs://post-service-r3a2dr4u4a-nw.a.run.app

    # Chat Service methods
    - selector: cheers.chat.v1.*
      address: grpcs://chat-service-r3a2dr4u4a-nw.a.run.app

    # Story Service methods
    - selector: cheers.story.v1.*
      address: grpcs://story-service-r3a2dr4u4a-nw.a.run.app

    # Activity Service methods
    - selector: cheers.activity.v1.*
      address: grpcs://activity-service-r3a2dr4u4a-nw.a.run.app

    # Notification Service methods
    - selector: cheers.notification.v1.*
      address: grpcs://notification-service-r3a2dr4u4a-nw.a.run.app

    # Ticket Service methods
    - selector: cheers.ticket.v1.*
      address: grpcs://ticket-service-r3a2dr4u4a-nw.a.run.app

    # Comment Service methods
    - selector: cheers.comment.v1.*
      address: grpcs://comment-service-r3a2dr4u4a-nw.a.run.app

    # Friendship Service methods
    - selector: cheers.friendship.v1.*
      address: grpcs://friendship-service-r3a2dr4u4a-nw.a.run.app