# HTTP rules for User

type: google.api.Service
config_version: 3

# Name of the service configuration.
name: android.apigateway.cheers-a275e.cloud.goog

# HTTP rules define translation from HTTP/REST/JSON to gRPC. With these rules
# HTTP/REST/JSON clients will be able to call the User service.
http:
  rules:
    - selector: cheers.party.v1.*
      post: /v1/parties
    - selector: cheers.post.v1.*
      post: /v1/posts