type: google.api.Service
config_version: 3
name: android.apigateway.cheers-a275e.cloud.goog
title: Cheers API
apis:
  - name: cheers.post.v1.PostService
  - name: cheers.party.v1.PartyService
usage:
  rules:
    # All methods can be called without an API Key.
    - selector: "*"
      allow_unregistered_calls: true
authentication:
  providers:
    - id: firebase
      jwks_uri: https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com
      issuer: https://securetoken.google.com/cheers-a275e
      audiences: "cheers-a275e"
  rules:
    - selector: "*"
      requirements:
        - provider_id: firebase
backend:
  rules:
    # Party Service methods
    - selector: cheers.party.v1.*
      address: grpcs://party-service-r3a2dr4u4a-nw.a.run.app

    # Post Service methods
    - selector: cheers.post.v1.*
      address: grpcs://post-service-r3a2dr4u4a-nw.a.run.app