steps:
  # List microservices that changed
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        git fetch --depth=2 origin main
        git  log
        git diff --name-only main HEAD | grep "services/" | cut -d/ -f2 | sort | uniq > /workspace/diff.txt

  # Run cloud builds of every microservice that changed
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        while read line
        do 
        config="services/${line}/cloudbuild.yaml"
        echo $config
        if [[ ! -f "${config}" ]]; then
         echo "no such file"
         continue
        fi
        gcloud builds submit $line --config=${config}
        done < /workspace/diff.txt

options:
 logging: CLOUD_LOGGING_ONLY