// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package userpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Verified             bool     `protobuf:"varint,4,opt,name=verified,proto3" json:"verified,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Picture              string   `protobuf:"bytes,6,opt,name=picture,proto3" json:"picture,omitempty"`
	Bio                  string   `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	Website              string   `protobuf:"bytes,8,opt,name=website,proto3" json:"website,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,9,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Created              float32  `protobuf:"fixed32,10,opt,name=created,proto3" json:"created,omitempty"`
	RegistrationTokens   []string `protobuf:"bytes,11,rep,name=registration_tokens,json=registrationTokens,proto3" json:"registration_tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *User) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetCreated() float32 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *User) GetRegistrationTokens() []string {
	if m != nil {
		return m.RegistrationTokens
	}
	return nil
}

type GetUserRequest struct {
	// Types that are valid to be assigned to Identification:
	//	*GetUserRequest_UserId
	//	*GetUserRequest_Username
	Identification       isGetUserRequest_Identification `protobuf_oneof:"identification"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{1}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

type isGetUserRequest_Identification interface {
	isGetUserRequest_Identification()
}

type GetUserRequest_UserId struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof"`
}

type GetUserRequest_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

func (*GetUserRequest_UserId) isGetUserRequest_Identification() {}

func (*GetUserRequest_Username) isGetUserRequest_Identification() {}

func (m *GetUserRequest) GetIdentification() isGetUserRequest_Identification {
	if m != nil {
		return m.Identification
	}
	return nil
}

func (m *GetUserRequest) GetUserId() string {
	if x, ok := m.GetIdentification().(*GetUserRequest_UserId); ok {
		return x.UserId
	}
	return ""
}

func (m *GetUserRequest) GetUsername() string {
	if x, ok := m.GetIdentification().(*GetUserRequest_Username); ok {
		return x.Username
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetUserRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetUserRequest_UserId)(nil),
		(*GetUserRequest_Username)(nil),
	}
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	PostCount            int64    `protobuf:"varint,2,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	FollowBack           bool     `protobuf:"varint,3,opt,name=follow_back,json=followBack,proto3" json:"follow_back,omitempty"`
	FollowingCount       int64    `protobuf:"varint,4,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	FollowersCount       int64    `protobuf:"varint,5,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	StoryState           string   `protobuf:"bytes,6,opt,name=story_state,json=storyState,proto3" json:"story_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{2}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetUserResponse) GetPostCount() int64 {
	if m != nil {
		return m.PostCount
	}
	return 0
}

func (m *GetUserResponse) GetFollowBack() bool {
	if m != nil {
		return m.FollowBack
	}
	return false
}

func (m *GetUserResponse) GetFollowingCount() int64 {
	if m != nil {
		return m.FollowingCount
	}
	return 0
}

func (m *GetUserResponse) GetFollowersCount() int64 {
	if m != nil {
		return m.FollowersCount
	}
	return 0
}

func (m *GetUserResponse) GetStoryState() string {
	if m != nil {
		return m.StoryState
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "userpb.User")
	proto.RegisterType((*GetUserRequest)(nil), "userpb.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "userpb.GetUserResponse")
}

func init() {
	proto.RegisterFile("proto/user.proto", fileDescriptor_d570e3e37e5899c5)
}

var fileDescriptor_d570e3e37e5899c5 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xcd, 0x8e, 0xd3, 0x40,
	0x0c, 0xc7, 0x69, 0x9a, 0xb6, 0xa9, 0xb3, 0xea, 0x56, 0x06, 0xc1, 0xb0, 0x02, 0x11, 0x7a, 0xa1,
	0xa7, 0x56, 0x5a, 0x6e, 0x1c, 0xcb, 0x01, 0xf6, 0xc2, 0x21, 0x0b, 0x17, 0x38, 0x44, 0xf9, 0x70,
	0x97, 0x51, 0xdb, 0x99, 0x30, 0x33, 0xd9, 0x15, 0xef, 0xc4, 0x73, 0xf1, 0x1c, 0x68, 0x9c, 0x0f,
	0x15, 0xed, 0xcd, 0xff, 0xdf, 0xdf, 0x63, 0xcb, 0xf6, 0xc0, 0xb2, 0x36, 0xda, 0xe9, 0x6d, 0x63,
	0xc9, 0x6c, 0x38, 0xc4, 0xa9, 0x8f, 0xeb, 0x62, 0xf5, 0x27, 0x80, 0xf0, 0x9b, 0x25, 0x83, 0x0b,
	0x08, 0x64, 0x25, 0x46, 0xc9, 0x68, 0x3d, 0x4f, 0x03, 0x59, 0x21, 0x42, 0xa8, 0xf2, 0x13, 0x89,
	0x80, 0x09, 0xc7, 0xf8, 0x0c, 0x26, 0x74, 0xca, 0xe5, 0x51, 0x8c, 0x19, 0xb6, 0x02, 0xaf, 0x20,
	0xba, 0x27, 0x23, 0xf7, 0x92, 0x2a, 0x11, 0x26, 0xa3, 0x75, 0x94, 0x0e, 0xda, 0x7b, 0xbe, 0x11,
	0x57, 0x9a, 0xf0, 0xa3, 0x41, 0xa3, 0x80, 0x59, 0x2d, 0x4b, 0xd7, 0x18, 0x12, 0x53, 0xb6, 0x7a,
	0x89, 0x4b, 0x18, 0x17, 0x52, 0x8b, 0x19, 0x53, 0x1f, 0xfa, 0xdc, 0x07, 0x2a, 0xac, 0x74, 0x24,
	0xa2, 0x36, 0xb7, 0x93, 0xf8, 0x16, 0x2e, 0xea, 0x9f, 0x5a, 0x51, 0xa6, 0x9a, 0x53, 0x41, 0x46,
	0xcc, 0xd9, 0x8e, 0x99, 0x7d, 0x61, 0xe4, 0x1f, 0x97, 0x86, 0x72, 0x47, 0x95, 0x80, 0x64, 0xb4,
	0x0e, 0xd2, 0x5e, 0xe2, 0x16, 0x9e, 0x1a, 0xba, 0x93, 0xd6, 0x99, 0xdc, 0x49, 0xad, 0x32, 0xa7,
	0x0f, 0xa4, 0xac, 0x88, 0x93, 0xf1, 0x7a, 0x9e, 0xe2, 0xb9, 0xf5, 0x95, 0x9d, 0xd5, 0x0f, 0x58,
	0x7c, 0x22, 0xe7, 0x17, 0x96, 0xd2, 0xaf, 0x86, 0xac, 0xc3, 0x97, 0x30, 0xf3, 0x13, 0x65, 0xfd,
	0xf2, 0x3e, 0x3f, 0x49, 0x79, 0xb7, 0x37, 0x15, 0xbe, 0x3a, 0x1b, 0x3e, 0xe8, 0xbc, 0x81, 0xec,
	0x96, 0xb0, 0x90, 0x15, 0x29, 0x27, 0xf7, 0xb2, 0xe4, 0x16, 0xab, 0xbf, 0x23, 0xb8, 0x1c, 0xaa,
	0xdb, 0x5a, 0x2b, 0x4b, 0x98, 0x40, 0xe8, 0x5f, 0x70, 0xed, 0xf8, 0xfa, 0x62, 0xd3, 0x9e, 0x6d,
	0xc3, 0x39, 0xec, 0xe0, 0x6b, 0x80, 0x5a, 0x5b, 0x97, 0x95, 0xba, 0x51, 0x8e, 0xfb, 0x8c, 0xd3,
	0xb9, 0x27, 0x1f, 0x3d, 0xc0, 0x37, 0x10, 0xef, 0xf5, 0xf1, 0xa8, 0x1f, 0xb2, 0x22, 0x2f, 0x0f,
	0x7c, 0xb9, 0x28, 0x85, 0x16, 0xed, 0xf2, 0xf2, 0x80, 0xef, 0xe0, 0xb2, 0x55, 0x52, 0xdd, 0x75,
	0x45, 0x42, 0x2e, 0xb2, 0x18, 0x70, 0x5b, 0x69, 0x48, 0x24, 0x63, 0xbb, 0xc4, 0xc9, 0x79, 0x22,
	0x19, 0x3b, 0xb4, 0xb4, 0x4e, 0x9b, 0xdf, 0x99, 0x75, 0xb9, 0xeb, 0x8f, 0x0b, 0x8c, 0x6e, 0x3d,
	0xb9, 0xbe, 0x81, 0xd8, 0x0f, 0x70, 0x4b, 0xe6, 0x5e, 0x96, 0x84, 0x1f, 0x60, 0xd6, 0x8d, 0x8d,
	0xcf, 0xfb, 0x01, 0xff, 0xdf, 0xf2, 0xd5, 0x8b, 0x47, 0xbc, 0xdd, 0xcf, 0x0e, 0xbe, 0x47, 0x9b,
	0x6d, 0xeb, 0x15, 0x53, 0xfe, 0xda, 0xef, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xf2, 0x05,
	0x16, 0xee, 0x02, 0x00, 0x00,
}
