// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: cheers/story/v1/story_service.proto

package story

import (
	story "github.com/salazarhugo/cheers1/genproto/cheers/type/story"
	user "github.com/salazarhugo/cheers1/genproto/cheers/type/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateStoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Story *story.Story `protobuf:"bytes,1,opt,name=story,proto3" json:"story,omitempty"`
}

func (x *CreateStoryRequest) Reset() {
	*x = CreateStoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoryRequest) ProtoMessage() {}

func (x *CreateStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoryRequest.ProtoReflect.Descriptor instead.
func (*CreateStoryRequest) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateStoryRequest) GetStory() *story.Story {
	if x != nil {
		return x.Story
	}
	return nil
}

type GetStoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetStoryRequest) Reset() {
	*x = GetStoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoryRequest) ProtoMessage() {}

func (x *GetStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoryRequest.ProtoReflect.Descriptor instead.
func (*GetStoryRequest) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetStoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateStoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Story *story.Story `protobuf:"bytes,1,opt,name=story,proto3" json:"story,omitempty"`
}

func (x *UpdateStoryRequest) Reset() {
	*x = UpdateStoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStoryRequest) ProtoMessage() {}

func (x *UpdateStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateStoryRequest) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateStoryRequest) GetStory() *story.Story {
	if x != nil {
		return x.Story
	}
	return nil
}

type DeleteStoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteStoryRequest) Reset() {
	*x = DeleteStoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoryRequest) ProtoMessage() {}

func (x *DeleteStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteStoryRequest) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteStoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FeedStoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parent   string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Page     int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *FeedStoryRequest) Reset() {
	*x = FeedStoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedStoryRequest) ProtoMessage() {}

func (x *FeedStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedStoryRequest.ProtoReflect.Descriptor instead.
func (*FeedStoryRequest) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{4}
}

func (x *FeedStoryRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *FeedStoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FeedStoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type FeedStoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stories       []*StoryResponse `protobuf:"bytes,1,rep,name=stories,proto3" json:"stories,omitempty"`
	NextPageToken string           `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
}

func (x *FeedStoryResponse) Reset() {
	*x = FeedStoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedStoryResponse) ProtoMessage() {}

func (x *FeedStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedStoryResponse.ProtoReflect.Descriptor instead.
func (*FeedStoryResponse) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{5}
}

func (x *FeedStoryResponse) GetStories() []*StoryResponse {
	if x != nil {
		return x.Stories
	}
	return nil
}

func (x *FeedStoryResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ViewStoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ViewStoryRequest) Reset() {
	*x = ViewStoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewStoryRequest) ProtoMessage() {}

func (x *ViewStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewStoryRequest.ProtoReflect.Descriptor instead.
func (*ViewStoryRequest) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{6}
}

func (x *ViewStoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ViewStoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ViewStoryResponse) Reset() {
	*x = ViewStoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewStoryResponse) ProtoMessage() {}

func (x *ViewStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewStoryResponse.ProtoReflect.Descriptor instead.
func (*ViewStoryResponse) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{7}
}

func (x *ViewStoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LikeStoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *LikeStoryRequest) Reset() {
	*x = LikeStoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeStoryRequest) ProtoMessage() {}

func (x *LikeStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeStoryRequest.ProtoReflect.Descriptor instead.
func (*LikeStoryRequest) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{8}
}

func (x *LikeStoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LikeStoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *LikeStoryResponse) Reset() {
	*x = LikeStoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeStoryResponse) ProtoMessage() {}

func (x *LikeStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeStoryResponse.ProtoReflect.Descriptor instead.
func (*LikeStoryResponse) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{9}
}

func (x *LikeStoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnlikeStoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UnlikeStoryRequest) Reset() {
	*x = UnlikeStoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnlikeStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeStoryRequest) ProtoMessage() {}

func (x *UnlikeStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeStoryRequest.ProtoReflect.Descriptor instead.
func (*UnlikeStoryRequest) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{10}
}

func (x *UnlikeStoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnlikeStoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UnlikeStoryResponse) Reset() {
	*x = UnlikeStoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnlikeStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeStoryResponse) ProtoMessage() {}

func (x *UnlikeStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeStoryResponse.ProtoReflect.Descriptor instead.
func (*UnlikeStoryResponse) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{11}
}

func (x *UnlikeStoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SaveStoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SaveStoryRequest) Reset() {
	*x = SaveStoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveStoryRequest) ProtoMessage() {}

func (x *SaveStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveStoryRequest.ProtoReflect.Descriptor instead.
func (*SaveStoryRequest) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{12}
}

func (x *SaveStoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SaveStoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SaveStoryResponse) Reset() {
	*x = SaveStoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveStoryResponse) ProtoMessage() {}

func (x *SaveStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveStoryResponse.ProtoReflect.Descriptor instead.
func (*SaveStoryResponse) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{13}
}

func (x *SaveStoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UnsaveStoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UnsaveStoryRequest) Reset() {
	*x = UnsaveStoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsaveStoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsaveStoryRequest) ProtoMessage() {}

func (x *UnsaveStoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsaveStoryRequest.ProtoReflect.Descriptor instead.
func (*UnsaveStoryRequest) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{14}
}

func (x *UnsaveStoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnsaveStoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UnsaveStoryResponse) Reset() {
	*x = UnsaveStoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsaveStoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsaveStoryResponse) ProtoMessage() {}

func (x *UnsaveStoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsaveStoryResponse.ProtoReflect.Descriptor instead.
func (*UnsaveStoryResponse) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{15}
}

func (x *UnsaveStoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Story       *story.Story `protobuf:"bytes,1,opt,name=story,proto3" json:"story,omitempty"`
	User        *user.User   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	LikeCount   int64        `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ViewerCount int64        `protobuf:"varint,4,opt,name=viewer_count,json=viewerCount,proto3" json:"viewer_count,omitempty"`
	HasLiked    bool         `protobuf:"varint,5,opt,name=has_liked,json=hasLiked,proto3" json:"has_liked,omitempty"`
}

func (x *StoryResponse) Reset() {
	*x = StoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cheers_story_v1_story_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryResponse) ProtoMessage() {}

func (x *StoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cheers_story_v1_story_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryResponse.ProtoReflect.Descriptor instead.
func (*StoryResponse) Descriptor() ([]byte, []int) {
	return file_cheers_story_v1_story_service_proto_rawDescGZIP(), []int{16}
}

func (x *StoryResponse) GetStory() *story.Story {
	if x != nil {
		return x.Story
	}
	return nil
}

func (x *StoryResponse) GetUser() *user.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *StoryResponse) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *StoryResponse) GetViewerCount() int64 {
	if x != nil {
		return x.ViewerCount
	}
	return 0
}

func (x *StoryResponse) GetHasLiked() bool {
	if x != nil {
		return x.HasLiked
	}
	return false
}

var File_cheers_story_v1_story_service_proto protoreflect.FileDescriptor

var file_cheers_story_v1_story_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x1a, 0x1d, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x2f, 0x74, 0x79,
	0x70, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x3e, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22,
	0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x3e, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x05, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5b, 0x0a, 0x10, 0x46, 0x65, 0x65, 0x64,
	0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x75, 0x0a, 0x11, 0x46, 0x65, 0x65, 0x64, 0x53, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x73, 0x74,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x68,
	0x65, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x73, 0x74, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e,
	0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x22, 0x0a, 0x10,
	0x56, 0x69, 0x65, 0x77, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x2d, 0x0a, 0x11, 0x56, 0x69, 0x65, 0x77, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22,
	0x22, 0x0a, 0x10, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x11, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x22, 0x24, 0x0a, 0x12, 0x55, 0x6e, 0x6c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x55, 0x6e, 0x6c, 0x69,
	0x6b, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x22, 0x0a, 0x10, 0x53, 0x61, 0x76,
	0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a,
	0x11, 0x53, 0x61, 0x76, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x24, 0x0a, 0x12,
	0x55, 0x6e, 0x73, 0x61, 0x76, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x55, 0x6e, 0x73, 0x61, 0x76, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0xbf, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12,
	0x25, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x69, 0x6b, 0x65,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x76, 0x69, 0x65,
	0x77, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x5f,
	0x6c, 0x69, 0x6b, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x61, 0x73,
	0x4c, 0x69, 0x6b, 0x65, 0x64, 0x32, 0xd4, 0x06, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x23, 0x2e, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x68, 0x65,
	0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x08, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x2e, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x68, 0x65, 0x65, 0x72,
	0x73, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x23, 0x2e, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63,
	0x68, 0x65, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0b,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x23, 0x2e, 0x63, 0x68,
	0x65, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x52, 0x0a, 0x09, 0x46, 0x65, 0x65, 0x64,
	0x53, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x21, 0x2e, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x53, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x68, 0x65, 0x65, 0x72,
	0x73, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x53,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x09,
	0x56, 0x69, 0x65, 0x77, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x21, 0x2e, 0x63, 0x68, 0x65, 0x65,
	0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x65, 0x77,
	0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63,
	0x68, 0x65, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x56,
	0x69, 0x65, 0x77, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x52, 0x0a, 0x09, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x21, 0x2e,
	0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0b, 0x55, 0x6e, 0x6c, 0x69, 0x6b, 0x65, 0x53, 0x74,
	0x6f, 0x72, 0x79, 0x12, 0x23, 0x2e, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x6c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x68, 0x65, 0x65, 0x72,
	0x73, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x6c, 0x69, 0x6b,
	0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52,
	0x0a, 0x09, 0x53, 0x61, 0x76, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x21, 0x2e, 0x63, 0x68,
	0x65, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61,
	0x76, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x61, 0x76, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x58, 0x0a, 0x0b, 0x55, 0x6e, 0x73, 0x61, 0x76, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x79, 0x12, 0x23, 0x2e, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x73, 0x61, 0x76, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x73, 0x61, 0x76, 0x65, 0x53,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x41, 0x50, 0x01,
	0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x61, 0x6c,
	0x61, 0x7a, 0x61, 0x72, 0x68, 0x75, 0x67, 0x6f, 0x2f, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73, 0x31,
	0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x65, 0x65, 0x72, 0x73,
	0x2f, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cheers_story_v1_story_service_proto_rawDescOnce sync.Once
	file_cheers_story_v1_story_service_proto_rawDescData = file_cheers_story_v1_story_service_proto_rawDesc
)

func file_cheers_story_v1_story_service_proto_rawDescGZIP() []byte {
	file_cheers_story_v1_story_service_proto_rawDescOnce.Do(func() {
		file_cheers_story_v1_story_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_cheers_story_v1_story_service_proto_rawDescData)
	})
	return file_cheers_story_v1_story_service_proto_rawDescData
}

var file_cheers_story_v1_story_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_cheers_story_v1_story_service_proto_goTypes = []interface{}{
	(*CreateStoryRequest)(nil),  // 0: cheers.story.v1.CreateStoryRequest
	(*GetStoryRequest)(nil),     // 1: cheers.story.v1.GetStoryRequest
	(*UpdateStoryRequest)(nil),  // 2: cheers.story.v1.UpdateStoryRequest
	(*DeleteStoryRequest)(nil),  // 3: cheers.story.v1.DeleteStoryRequest
	(*FeedStoryRequest)(nil),    // 4: cheers.story.v1.FeedStoryRequest
	(*FeedStoryResponse)(nil),   // 5: cheers.story.v1.FeedStoryResponse
	(*ViewStoryRequest)(nil),    // 6: cheers.story.v1.ViewStoryRequest
	(*ViewStoryResponse)(nil),   // 7: cheers.story.v1.ViewStoryResponse
	(*LikeStoryRequest)(nil),    // 8: cheers.story.v1.LikeStoryRequest
	(*LikeStoryResponse)(nil),   // 9: cheers.story.v1.LikeStoryResponse
	(*UnlikeStoryRequest)(nil),  // 10: cheers.story.v1.UnlikeStoryRequest
	(*UnlikeStoryResponse)(nil), // 11: cheers.story.v1.UnlikeStoryResponse
	(*SaveStoryRequest)(nil),    // 12: cheers.story.v1.SaveStoryRequest
	(*SaveStoryResponse)(nil),   // 13: cheers.story.v1.SaveStoryResponse
	(*UnsaveStoryRequest)(nil),  // 14: cheers.story.v1.UnsaveStoryRequest
	(*UnsaveStoryResponse)(nil), // 15: cheers.story.v1.UnsaveStoryResponse
	(*StoryResponse)(nil),       // 16: cheers.story.v1.StoryResponse
	(*story.Story)(nil),         // 17: cheers.type.Story
	(*user.User)(nil),           // 18: cheers.type.User
	(*emptypb.Empty)(nil),       // 19: google.protobuf.Empty
}
var file_cheers_story_v1_story_service_proto_depIdxs = []int32{
	17, // 0: cheers.story.v1.CreateStoryRequest.story:type_name -> cheers.type.Story
	17, // 1: cheers.story.v1.UpdateStoryRequest.story:type_name -> cheers.type.Story
	16, // 2: cheers.story.v1.FeedStoryResponse.stories:type_name -> cheers.story.v1.StoryResponse
	17, // 3: cheers.story.v1.StoryResponse.story:type_name -> cheers.type.Story
	18, // 4: cheers.story.v1.StoryResponse.user:type_name -> cheers.type.User
	0,  // 5: cheers.story.v1.StoryService.CreateStory:input_type -> cheers.story.v1.CreateStoryRequest
	1,  // 6: cheers.story.v1.StoryService.GetStory:input_type -> cheers.story.v1.GetStoryRequest
	2,  // 7: cheers.story.v1.StoryService.UpdateStory:input_type -> cheers.story.v1.UpdateStoryRequest
	3,  // 8: cheers.story.v1.StoryService.DeleteStory:input_type -> cheers.story.v1.DeleteStoryRequest
	4,  // 9: cheers.story.v1.StoryService.FeedStory:input_type -> cheers.story.v1.FeedStoryRequest
	6,  // 10: cheers.story.v1.StoryService.ViewStory:input_type -> cheers.story.v1.ViewStoryRequest
	8,  // 11: cheers.story.v1.StoryService.LikeStory:input_type -> cheers.story.v1.LikeStoryRequest
	10, // 12: cheers.story.v1.StoryService.UnlikeStory:input_type -> cheers.story.v1.UnlikeStoryRequest
	12, // 13: cheers.story.v1.StoryService.SaveStory:input_type -> cheers.story.v1.SaveStoryRequest
	14, // 14: cheers.story.v1.StoryService.UnsaveStory:input_type -> cheers.story.v1.UnsaveStoryRequest
	16, // 15: cheers.story.v1.StoryService.CreateStory:output_type -> cheers.story.v1.StoryResponse
	16, // 16: cheers.story.v1.StoryService.GetStory:output_type -> cheers.story.v1.StoryResponse
	16, // 17: cheers.story.v1.StoryService.UpdateStory:output_type -> cheers.story.v1.StoryResponse
	19, // 18: cheers.story.v1.StoryService.DeleteStory:output_type -> google.protobuf.Empty
	5,  // 19: cheers.story.v1.StoryService.FeedStory:output_type -> cheers.story.v1.FeedStoryResponse
	7,  // 20: cheers.story.v1.StoryService.ViewStory:output_type -> cheers.story.v1.ViewStoryResponse
	9,  // 21: cheers.story.v1.StoryService.LikeStory:output_type -> cheers.story.v1.LikeStoryResponse
	11, // 22: cheers.story.v1.StoryService.UnlikeStory:output_type -> cheers.story.v1.UnlikeStoryResponse
	13, // 23: cheers.story.v1.StoryService.SaveStory:output_type -> cheers.story.v1.SaveStoryResponse
	15, // 24: cheers.story.v1.StoryService.UnsaveStory:output_type -> cheers.story.v1.UnsaveStoryResponse
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_cheers_story_v1_story_service_proto_init() }
func file_cheers_story_v1_story_service_proto_init() {
	if File_cheers_story_v1_story_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cheers_story_v1_story_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cheers_story_v1_story_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cheers_story_v1_story_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cheers_story_v1_story_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteStoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cheers_story_v1_story_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedStoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cheers_story_v1_story_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedStoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cheers_story_v1_story_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewStoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cheers_story_v1_story_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewStoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cheers_story_v1_story_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeStoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cheers_story_v1_story_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeStoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cheers_story_v1_story_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnlikeStoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cheers_story_v1_story_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnlikeStoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cheers_story_v1_story_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveStoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cheers_story_v1_story_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveStoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cheers_story_v1_story_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnsaveStoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cheers_story_v1_story_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnsaveStoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cheers_story_v1_story_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cheers_story_v1_story_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cheers_story_v1_story_service_proto_goTypes,
		DependencyIndexes: file_cheers_story_v1_story_service_proto_depIdxs,
		MessageInfos:      file_cheers_story_v1_story_service_proto_msgTypes,
	}.Build()
	File_cheers_story_v1_story_service_proto = out.File
	file_cheers_story_v1_story_service_proto_rawDesc = nil
	file_cheers_story_v1_story_service_proto_goTypes = nil
	file_cheers_story_v1_story_service_proto_depIdxs = nil
}
