steps:
  # Run tests
  - name: golang:1.21
    entrypoint: /bin/bash
    args:
      - go test -timeout 1m -v
    secretEnv: ['NEO4J_URI', 'NEO4J_PASSWORD']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/NEO4J_URI/versions/latest
    env: 'NEO4J_URI'
  - versionName: projects/$PROJECT_ID/secrets/NEO4J_PASSWORD/versions/latest
    env: 'NEO4J_PASSWORD'
