steps:
  # Bazel Build
  - name: 'cockroachdb/bazel'
    entrypoint: 'bazel'
    args: ['build', '//cmd/app:app']
    secretEnv: ['NEO4J_URI', 'NEO4J_PASSWORD']
    dir: 'services/user-service'

  # Bazel Test
  - name: 'cockroachdb/bazel'
    entrypoint: 'bazel'
    args: ['test', '//...']
    secretEnv: ['NEO4J_URI', 'NEO4J_PASSWORD']
    dir: 'services/user-service'

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/myimage:$SHORT_SHA', '.']
    dir: 'services/user-service'

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/myimage:$SHORT_SHA']
    dir: 'services/user-service'

# Store images in Google Artifact Registry
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/myimage:$SHORT_SHA
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/NEO4J_URI/versions/latest
    env: 'NEO4J_URI'
  - versionName: projects/$PROJECT_ID/secrets/NEO4J_PASSWORD/versions/latest
    env: 'NEO4J_PASSWORD'
