GATEWAY_URL=https://android-gateway-clzdlli7.nw.gateway.dev
TOKEN=eyJhbGciOiJSUzI1NiIsImtpZCI6IjU4NWI5MGI1OWM2YjM2ZDNjOTBkZjBlOTEwNDQ1M2U2MmY4ODdmNzciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY2hlZXJzLWEyNzVlIiwiYXVkIjoiY2hlZXJzLWEyNzVlIiwiYXV0aF90aW1lIjoxNjYxNzc0ODUzLCJ1c2VyX2lkIjoid29GdHBYVVQ5aVRVSU1Zc3NHNWtJSDVhbmg0MyIsInN1YiI6IndvRnRwWFVUOWlUVUlNWXNzRzVrSUg1YW5oNDMiLCJpYXQiOjE2NjQ1NDU5NDAsImV4cCI6MTY2NDU0OTU0MCwiZW1haWwiOiJodWdvYnJvY2s3NCtjaGVlcnNAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiaHVnb2Jyb2NrNzQrY2hlZXJzQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.f8XzzvEbJgwGyhg0VurrMEuMBQPQQQGMMpEWqU43sQnE1CUEPNqMSmYpfbb3RPMUh2fg-v-8JSySgV9JcaEs0tCAW1PJaItckf_QffqZ8MJ2oxmliFV6hznc4JiCO3kFHHm7eAKKN0ladhyQlMe6ND27nz47GzWdYzSYsW0RbfFlnLzUgXv6tMynaA85T4rVyoHwe0ZYSYbPE6dhuJchjf3y7O162AlqYpH3l3dsCON0BrhvZE8Svza88K92Sg4f6QZylIr4GGHVrJofLHNw7VaqSGzYdHcJ9AnH8R1j-jGeNRsiw9yCX-vrSOC8CAOA-fbXUHjqmQfMI3NL_wGRiA

#curl -d client_id=$CLIENT_ID -d client_secret=$CLIENT_SECRET -d grant_type=authorization_code -d redirect_uri=urn:ietf:wg:oauth:2.0:oob -d code=4/AABvK4EPc__nckJBK9UGFIhhls_69SBAyidj8J_o3Zz5-VJN6nz54ew https://accounts.google.com/o/oauth2/token
curl --request GET \
  --header "Authorization: Bearer $TOKEN" \
  "$GATEWAY_URL/users/android"

curl --request POST \
  --header "Authorization: Bearer $TOKEN" \
  "$GATEWAY_URL/parties"

curl --request DELETE \
  --header "Authorization: Bearer $TOKEN" \
  "$GATEWAY_URL/parties"
