// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userpb/user.proto

package userpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Verified             bool     `protobuf:"varint,4,opt,name=verified,proto3" json:"verified,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Picture              string   `protobuf:"bytes,6,opt,name=picture,proto3" json:"picture,omitempty"`
	Bio                  string   `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	Website              string   `protobuf:"bytes,8,opt,name=website,proto3" json:"website,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,9,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Created              float32  `protobuf:"fixed32,10,opt,name=created,proto3" json:"created,omitempty"`
	RegistrationTokens   []string `protobuf:"bytes,11,rep,name=registration_tokens,json=registrationTokens,proto3" json:"registration_tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_2eaba19047509177, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *User) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetCreated() float32 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *User) GetRegistrationTokens() []string {
	if m != nil {
		return m.RegistrationTokens
	}
	return nil
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	PostCount            int64    `protobuf:"varint,2,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	FollowBack           bool     `protobuf:"varint,3,opt,name=follow_back,json=followBack,proto3" json:"follow_back,omitempty"`
	FollowingCount       int64    `protobuf:"varint,4,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	FollowersCount       int64    `protobuf:"varint,5,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	StoryState           string   `protobuf:"bytes,6,opt,name=story_state,json=storyState,proto3" json:"story_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2eaba19047509177, []int{1}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetUserResponse) GetPostCount() int64 {
	if m != nil {
		return m.PostCount
	}
	return 0
}

func (m *GetUserResponse) GetFollowBack() bool {
	if m != nil {
		return m.FollowBack
	}
	return false
}

func (m *GetUserResponse) GetFollowingCount() int64 {
	if m != nil {
		return m.FollowingCount
	}
	return 0
}

func (m *GetUserResponse) GetFollowersCount() int64 {
	if m != nil {
		return m.FollowersCount
	}
	return 0
}

func (m *GetUserResponse) GetStoryState() string {
	if m != nil {
		return m.StoryState
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "userpb.User")
	proto.RegisterType((*GetUserResponse)(nil), "userpb.GetUserResponse")
}

func init() {
	proto.RegisterFile("userpb/user.proto", fileDescriptor_2eaba19047509177)
}

var fileDescriptor_2eaba19047509177 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x92, 0x4b, 0xce, 0xd3, 0x30,
	0x14, 0x85, 0x95, 0x47, 0xdb, 0xe4, 0xa6, 0x6a, 0xc1, 0x80, 0xb0, 0x90, 0x10, 0xa1, 0x13, 0x32,
	0x21, 0x95, 0x60, 0x07, 0x65, 0xc0, 0x8c, 0x41, 0x80, 0x09, 0x93, 0x28, 0x8f, 0xdb, 0x62, 0xb5,
	0xb5, 0x23, 0xdb, 0x69, 0xc5, 0x9e, 0x58, 0xd7, 0xbf, 0x8e, 0x5f, 0xbe, 0x6e, 0xa3, 0x8e, 0xec,
	0xf3, 0x9d, 0xe3, 0x6b, 0xf9, 0xc8, 0xf0, 0x72, 0x34, 0xa8, 0x87, 0x76, 0xeb, 0x96, 0x72, 0xd0,
	0xca, 0x2a, 0x36, 0xf7, 0x68, 0xf3, 0x3f, 0x84, 0xf8, 0xb7, 0x41, 0xcd, 0x56, 0x10, 0x8a, 0x9e,
	0x07, 0x79, 0x50, 0xa4, 0x55, 0x28, 0x7a, 0xc6, 0x20, 0x96, 0xcd, 0x19, 0x79, 0x48, 0x84, 0xf6,
	0xec, 0x35, 0xcc, 0xf0, 0xdc, 0x88, 0x13, 0x8f, 0x08, 0x7a, 0xc1, 0xde, 0x41, 0x72, 0x41, 0x2d,
	0xf6, 0x02, 0x7b, 0x1e, 0xe7, 0x41, 0x91, 0x54, 0x93, 0x76, 0x9e, 0xbb, 0x88, 0x26, 0xcd, 0xe8,
	0xd0, 0xa4, 0x19, 0x87, 0xc5, 0x20, 0x3a, 0x3b, 0x6a, 0xe4, 0x73, 0xb2, 0xee, 0x92, 0xbd, 0x80,
	0xa8, 0x15, 0x8a, 0x2f, 0x88, 0xba, 0xad, 0xcb, 0x5e, 0xb1, 0x35, 0xc2, 0x22, 0x4f, 0x7c, 0xf6,
	0x26, 0xd9, 0x47, 0x58, 0x0e, 0x7f, 0x95, 0xc4, 0x5a, 0x8e, 0xe7, 0x16, 0x35, 0x4f, 0xc9, 0xce,
	0x88, 0xfd, 0x20, 0xe4, 0x0e, 0x77, 0x1a, 0x1b, 0x8b, 0x3d, 0x87, 0x3c, 0x28, 0xc2, 0xea, 0x2e,
	0xd9, 0x16, 0x5e, 0x69, 0x3c, 0x08, 0x63, 0x75, 0x63, 0x85, 0x92, 0xb5, 0x55, 0x47, 0x94, 0x86,
	0x67, 0x79, 0x54, 0xa4, 0x15, 0x7b, 0xb4, 0x7e, 0x91, 0xb3, 0x79, 0x0a, 0x60, 0xfd, 0x1d, 0xad,
	0x6b, 0xac, 0x42, 0x33, 0x28, 0x69, 0x90, 0xe5, 0x10, 0xbb, 0x37, 0x51, 0x77, 0xd9, 0x97, 0x65,
	0xe9, 0x9b, 0x2d, 0x29, 0x43, 0x0e, 0x7b, 0x0f, 0x30, 0x28, 0x63, 0xeb, 0x4e, 0x8d, 0xd2, 0x52,
	0xa3, 0x51, 0x95, 0x3a, 0xf2, 0xcd, 0x01, 0xf6, 0x01, 0xb2, 0xbd, 0x3a, 0x9d, 0xd4, 0xb5, 0x6e,
	0x9b, 0xee, 0x48, 0xe5, 0x26, 0x15, 0x78, 0xb4, 0x6b, 0xba, 0x23, 0xfb, 0x04, 0x6b, 0xaf, 0x84,
	0x3c, 0xdc, 0x86, 0xc4, 0x34, 0x64, 0x35, 0x61, 0x3f, 0x69, 0x0a, 0xa2, 0x36, 0xb7, 0xe0, 0xec,
	0x31, 0x88, 0xda, 0x4c, 0x57, 0x1a, 0xab, 0xf4, 0xbf, 0xda, 0xd8, 0xc6, 0xde, 0xfb, 0x07, 0x42,
	0x3f, 0x1d, 0xd9, 0xbd, 0xfd, 0xf3, 0xa6, 0xa4, 0xff, 0xf2, 0xd9, 0xa0, 0xbe, 0x88, 0x0e, 0xb7,
	0xfe, 0x59, 0xed, 0x9c, 0xfe, 0xcf, 0xd7, 0xe7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xca, 0x92,
	0x42, 0x54, 0x02, 0x00, 0x00,
}
